version: "2"
services:
    base_environment:
        build: ./base_environment/
        image: base_environment
        container_name: base_environment
    database:
        build: ./database/
        image: database
        container_name: database
    zookeeper:
        image: "zookeeper:3.3.6"
        container_name: zookeeper
        ports:
          - "5006:2181"
        tty: true
    sqlredis:
        image: "database"
        container_name: sqlredis
        environment:
          - MYSQL_ROOT_PASSWORD=root
        volumes:
          - ./alphadeployy/mysqlog:/var/lib/mysql
          - ./database/mysql/libposition:/usr/lib64/mysql/plugin/
          - ./database/mysql/libhiredis.so.0.13:/usr/lib64/libhiredis.so.0.13
          - ./database/mysql/etc/my.cnf:/etc/my.cnf
          - ./alphadeployy/database:/docker-entrypoint-initdb.d/
          - ./database/entrypoint.sh:/entrypoint.sh
          - ./database/redis/redis.conf:/redis.conf
          - ./database/run.sh:/run.sh
        ports:
          - "3306:3306"
          - "6379:6379"
        command: ./run.sh
        tty: true
    redis:
        image: "redis"
        container_name: redis
        volumes:
          - ./database/redis/redis1.conf:/etc/redis.conf
        ports:
          - "5005:6379"
        command: redis-server /etc/redis.conf
        tty: true
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        volumes:
          - ./rabbitmq/init.sh:/init.sh
        ports:
          - "5672:5672"
          - "15672:15672"
        command: ./init.sh
        restart: "always"
    rmsource:
       image: "base_environment"
       container_name: rmsource
       volumes:
          - ./alphadeployy/riskmanagesource:/app/riskmanagesource
          - ./alphadeployy/configs/RMconfig.properties:/app/configs/RMconfig.properties
          - ./alphadeployy/dev-logs:/app/dev-logs
          - ./alphadeployy/logs:/app/logs
       depends_on:
          - sqlredis
          - redis
          - rabbitmq
       links:
          - "sqlredis"
          - "redis"
          - "rabbitmq"
       working_dir: /app/riskmanagesource
       command: java -jar riskmanage-source-V1.0.10.jar
       tty: true
    rmobj:
       image: "base_environment"
       container_name: rmobj
       volumes:
          - ./alphadeployy/riskmanagement:/app/riskmanagement
          - ./alphadeployy/configs/RMconfig.properties:/app/configs/RMconfig.properties
          - ./alphadeployy/dev-logs:/app/dev-logs
          - ./alphadeployy/logs:/app/logs
       depends_on:
          - sqlredis
          - redis
          - rabbitmq
       links:
          - "sqlredis"
          - "redis"
          - "rabbitmq"
       working_dir: /app/riskmanagement
       command: java -jar trad-rm-object-V1.0.10.jar
       tty: true
    rmrs:
       image: "base_environment"
       container_name: rmrs
       volumes:
          - ./alphadeployy/riskmanagereport:/app/riskmanagereport
          - ./alphadeployy/configs/RMconfig.properties:/app/configs/RMconfig.properties
          - ./alphadeployy/dev-logs:/app/dev-logs
          - ./alphadeployy/logs:/app/logs
       depends_on:
          - sqlredis
          - redis
          - rabbitmq
       links:
          - "sqlredis"
          - "redis"
          - "rabbitmq"
       working_dir: /app/riskmanagereport
       command: java -jar rmobject-reportserver-V1.0.10.jar
       tty: true
    cm:
        image: "base_environment"
        container_name: cm
        volumes:
          - ./alphadeployy/clientmanager:/app/clientmanager
          - ./alphadeployy/configs/config.properties:/app/configs/config.properties
          - ./alphadeployy/dev-logs:/app/dev-logs
          - ./alphadeployy/logs:/app/logs
        depends_on:
          - sqlredis
          - rabbitmq
        links:
          - "sqlredis"
          - "rabbitmq"
        working_dir: /app/clientmanager
        command: java -jar CM_V1.0.10.jar
        tty: true
    admin:
       image: "base_environment"
       container_name: admin
       volumes:
          - ./alphadeployy/netmanager:/app/netmanager
          - ./alphadeployy/adminservice:/app/adminservice
          - ./alphadeployy/configs/config.properties:/app/configs/config.properties
          - ./alphadeployy/dev-logs:/app/dev-logs
          - ./alphadeployy/logs:/app/logs
       depends_on:
          - sqlredis
          - rabbitmq
          - zookeeper
       links:
          - "sqlredis"
          - "rabbitmq"
          - "zookeeper"
       working_dir: /app/adminservice
       command: ./run.sh
       tty: true 
    ctl:
       image: "base_environment"
       container_name: ctl
       volumes:
          - ./alphadeployy/centrallogging:/app/centrallogging
          - ./alphadeployy/dev-logs:/app/dev-logs
       depends_on:
          - rabbitmq
       links:
          - "rabbitmq"
       working_dir: /app/centrallogging
       command: java -jar centrallogging-V1.0.10.jar &
       tty: true
    accumonitor:
       image: "base_environment"
       container_name: accumonitor
       volumes:
          - ./alphadeployy/accumonitor:/app/accumonitor
          - ./alphadeployy/dev-logs:/app/dev-logs
       depends_on:
          - rabbitmq
       links:
          - "rabbitmq"
       working_dir: /app/accumonitor
       command: java -jar accumonitor-V1.0.10.jar &
       tty: true
    tpm:
        image: "base_environment"
        container_name: tpm
        volumes:
          - ./alphadeployy/xservice:/app/xservice
          - ./alphadeployy/platformmonitor:/app/platformmonitor
          - ./alphadeployy/configs/platformmonitor.cfg:/app/configs/platformmonitor.cfg
          - ./alphadeployy/logs:/app/logs
        depends_on:
          - rabbitmq
        links:
          - "rabbitmq"
        working_dir: /app/platformmonitor
        command: ./run.sh
        tty: true
    mgsg5021:
        image: "base_environment"
        container_name: mgsg5021
        volumes:
          - ./alphadeployy/xservice:/app/xservice
          - ./alphadeployy/managementsg00:/app/managementsg
          - ./alphadeployy/configs/mgsg5021.cfg:/app/configs/mgsg5021.cfg
          - ./alphadeployy/managementsg01:/app/managementsg01
          - ./alphadeployy/configs/mgsg5022.cfg:/app/configs/mgsg5022.cfg
          - ./alphadeployy/managementsg02:/app/managementsg02
          - ./alphadeployy/configs/mgsg5023.cfg:/app/configs/mgsg5023.cfg
          - ./alphadeployy/logs:/app/logs
        depends_on:
          - rabbitmq
        ports:
          - "5021:5021"
          - "5022:5022"
          - "5023:5023"
        links:
          - "rabbitmq"
        working_dir: /app/managementsg
        command: ./run.sh
        tty: true
    sg5011:
        image: "base_environment"
        container_name: sg5011
        volumes:
          - ./alphadeployy/xservice:/app/xservice
          - ./alphadeployy/solutiongateway00:/app/solutiongateway00
          - ./alphadeployy/configs/solutiongateway5011.cfg:/app/configs/solutiongateway5011.cfg
          - ./alphadeployy/solutiongateway01:/app/solutiongateway01
          - ./alphadeployy/configs/solutiongateway5012.cfg:/app/configs/solutiongateway5012.cfg
          - ./alphadeployy/solutiongateway02:/app/solutiongateway02
          - ./alphadeployy/configs/solutiongateway5013.cfg:/app/configs/solutiongateway5013.cfg
          - ./alphadeployy/logs:/app/logs
        depends_on:
          - sqlredis
          - rabbitmq
        ports:
          - "5011:5011"
          - "5012:5012"
          - "5013:5013"
        links:
          - "sqlredis"
          - "rabbitmq"
        working_dir: /app/solutiongateway00
        command: ./run.sh
        tty: true
    te5151:
        image: "base_environment"
        container_name: te5151
        volumes:
          - ./alphadeployy/xservice:/app/xservice
          - ./alphadeployy/tradingengine00:/app/tradingengine00
          - ./alphadeployy/configs/tradingengine5151.cfg:/app/configs/tradingengine5151.cfg
          - ./alphadeployy/configs/TE_group_security.db:/app/configs/TE_group_security.db
          - ./alphadeployy/tradingengine01:/app/tradingengine01
          - ./alphadeployy/configs/tradingengine5152.cfg:/app/configs/tradingengine5152.cfg
          - ./alphadeployy/tradingengine02:/app/tradingengine02
          - ./alphadeployy/configs/tradingengine5153.cfg:/app/configs/tradingengine5153.cfg
          - ./alphadeployy/netfollower:/app/netfollower
          - ./alphadeployy/logs:/app/logs
          - ./alphadeployy/dev-logs:/app/dev-logs
        depends_on:
          - rabbitmq
          - zookeeper
        links:
          - "zookeeper"
          - "rabbitmq"
        working_dir: /app/tradingengine00
        command: ./run.sh
        tty: true
    sgd:
        image: "base_environment"
        container_name: sgd
        volumes:
          - ./alphadeployy/xservice:/app/xservice
          - ./alphadeployy/logs:/app/logs
          - ./alphadeployy/sgdistributor:/app/sgdistributor
        depends_on:
          - rabbitmq
        ports:
          - "5039:5039"
        links:
          - "rabbitmq"
        working_dir: /app/sgdistributor
        command: ./run.sh
        tty: true
    pm4141:
        image: "base_environment"
        container_name: pm4141
        volumes:
          - ./alphadeployy/xservice:/app/xservice
          - ./alphadeployy/positionmanagement00:/app/positionmanagement
          - ./alphadeployy/configs/positionmanagement4141.cfg:/app/configs/positionmanagement4141.cfg
          - ./alphadeployy/positionmanagement01:/app/positionmanagement01
          - ./alphadeployy/configs/positionmanagement4142.cfg:/app/configs/positionmanagement4142.cfg
          - ./alphadeployy/positionmanagement02:/app/positionmanagement02
          - ./alphadeployy/configs/positionmanagement4143.cfg:/app/configs/positionmanagement4143.cfg
          - ./alphadeployy/logs:/app/logs
        depends_on:
          - sqlredis
          - rabbitmq
        links:
          - "sqlredis"
          - "rabbitmq"
        working_dir: /app/positionmanagement
        command: ./run.sh
        tty: true
    mb:
        image: "base_environment"
        container_name: mb
        volumes:
          - ./alphadeployy/xservice:/app/xservice
          - ./alphadeployy/monitorbridge:/app/monitorbridge
          - ./alphadeployy/configs/monitorbridge.cfg:/app/configs/monitorbridge.cfg
          - ./alphadeployy/logs:/app/logs
        depends_on:
          - rabbitmq
        links:
          - "rabbitmq"
        working_dir: /app/monitorbridge
        command: ./run.sh
        tty: true
