#dataSource
dataSource:
  mysql:
    jdbcUrl: jdbc:mysql://localhost:3306/admdb?useSSL=false&allowMultiQueries=true
    driverClassName: com.mysql.jdbc.Driver
    userName: root
    password: root
  sqlite:
    jdbcUrl: jdbc:sqlite:group_security.db
    driverClassName: org.sqlite.JDBC
    
#rabbitmq
rabbit:
  host: 10.10.10.105
  port: 5672
  username: demo
  password: demo
  vhost: /demo
  exchange:
    t_node_grp:
      LOG: LOG.AD
      PASSWORD: PASSWORD.AD
      MANAGER: MANAGER.AD
      ADMIN: ADMIN.AD
      ACCOUNT: ACCOUNT.AD
      GROUP: GROUP.AD
      SECURITY: SECURITY.AD
      SYMBOL: SYMBOL.AD
      SYNCHDATA: SYNCHDATA.AD
    g_node_grp:
      test: test
  cm:
    exchange: admin_exc
    routingKey: admin2cm     
  adt:
    exchange: t_node_grp
      
default:
  payout: 80
  maximumBoAmountOfTradingCondition: 500000
  minimumBoAmountOfTradingCondition: 5
  timePeriod: 5;10;15;20;25;30;35;40;45