spring:
    datasource:
        url: jdbc:sqlite:sqlite/instantSignal.db
        driverClassName: org.sqlite.JDBC
    jpa:
        database-platform: cn.fintechstar.dcb.constant.SQLiteDialect
        show-sql: true
    redis:
        database: 2
        host: 52.66.45.64
        port: 5005
        password: hugo123456
        timeout: 2000
        pool:
            max-active: 20
            max-idle: 8
            min-idle: 0
    rabbitmq:
        listener:
            simple:
                acknowledge-mode: none
                
mq:
    host: 52.66.45.64
    port: 5672
    username: demo
    password: demo
    vhost: /demo
    instantExchange: t_node_grp
    instantSignalQueue: 
        queueName: REALTIME.DC
        routingKey: realtime_onez.*

candle: 
    sameCandleTime: 50
    maxSize: 2000   
    