server:
 port: 5082

spring:
 application:
  name: trad-nc-follower

eureka:
# instance:
#  hostname:localhost
#  registerWithEureka: false
#  fetchRegistry: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#mq
mq:
# host: 52.66.45.64 
 host: 35.154.147.154
 port: 5672
 vhost: /demo
 user: demo
 password: demo

#zookeeper
zk:
 hostport: 13.126.191.171:5006

#db.url=jdbc:sqlite:../v4_sgdistributor/sgd_urlmap.db  35.154.147.154:2181  
#db.url=jdbc:sqlite:../msg_tcp_srv/msg_service.db
#sqlite:../tradingengine/TE_group_security.db
#DB Settings
db:
 driverClassName: org.sqlite.JDBC
 url: jdbc:sqlite:../db/group_security.db
 dbType: sqlite
 username: root
 password: password
 initialSize: 10
 minIdle: 10
 maxActive: 30
 filters: stat