mq:
    host: 35.154.44.66
    port: 5672
    username: demo
    password: demo
    vhost: /demo
    exchange: t_node_grp
    queue: 
      login: LOGIN.#
      logout: LOGOUT.#
      userInfo: USERINFO.#
      ocposition: OCPOSITION.#
      pull: PULL.#
      forcelogout: FORCELOGOUT.#
    
        
spring:
    datasource:
        url: jdbc:sqlite:db.db
        driverClassName: org.sqlite.JDBC
        maximum-pool-size: 100
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5
        validation-query: SELECT 1
    jpa:
        database-platform: com.broctagon.accumonitor.util.SQLiteDialect
        show-sql: true
    rabbitmq:
        listener:
            simple: 
                acknowledge-mode: none