server:
 port: 5802

spring:
 application:
  name: trad-nc-follower

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#mq
mq:
 host: rabbitmq
 port: 5672
 vhost: /demo
 user: demo
 password: demo

#zookeeper
zk:
 hostport: 13.126.191.171:5006

#DB Settings
db:
 driverClassName: org.sqlite.JDBC
 url: jdbc:sqlite:/app/msg_tcp/msg_service.db
 dbType: sqlite
 username: root
 password: password
 initialSize: 5
 minIdle: 5
 maxActive: 5
 filters: stat

