version: "2"
services:
    base_environment:
        build: ./base_environment/
        image: base_environment
        container_name: base_environment
    redis:
        image: "redis"
        container_name: redis
        volumes:
          - ./database/redis/redis.conf:/etc/redis.conf
          - ./database/redis/datadir:/var/lib/redis
        ports:
          - "5005:6379"
        command: redis-server /etc/redis.conf
        restart: "always"
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: rabbitmq
        volumes:
          - ./rabbitmq/init.sh:/init.sh
        ports:
          - "5672:5672"
          - "15672:15672"
        command: ./init.sh
        restart: "always"
    DC:
        image: "base_environment"
        container_name: DC
        volumes:
          - ./MarketServer/datacenter:/app/datacenter
          - ./MarketServer/dev-logs:/app/dev-logs
        depends_on:
          - redis
          - rabbitmq
        links:
          - "redis"
          - "rabbitmq"
        working_dir: /app/datacenter
        command: java -jar DC-V1.0.11.jar
        tty: true
    DCB:
        image: "base_environment"
        container_name: DCB
        volumes:
          - ./MarketServer/datacenterbridge:/app/datacenterbridge
          - ./MarketServer/dev-logs:/app/dev-logs
        depends_on:
          - redis
        links:
          - "redis"
        working_dir: /app/datacenterbridge
        command: java -jar DCB-V1.0.11.jar
        tty: true
    onezeromarket:
        image: "base_environment"
        container_name: onezeromarket
        volumes:
          - ./MarketServer/xservice:/app/xservice
          - ./MarketServer/onezeromarket:/app/onezeromarket
          - ./MarketServer/logs:/app/logs
        depends_on:
          - rabbitmq
        links:
          - "rabbitmq"
        working_dir: /app/onezeromarket
#        command: ./run.sh
        tty: true
    msg_tcp:
        image: "base_environment"
        container_name: msg_tcp
        volumes:
          - ./MarketServer/networkconfiguration:/app/networkconfiguration
          - ./MarketServer/xservice:/app/xservice
          - ./MarketServer/msg_tcp:/app/msg_tcp
          - ./MarketServer/logs:/app/logs
          - ./MarketServer/dev-logs:/app/dev-logs
        depends_on:
          - rabbitmq
        ports:
          - "5038:5038"
        links:
          - "rabbitmq"
        working_dir: /app/msg_tcp
        command: ./run.sh
        tty: true
