spring:
    datasource:
        url: jdbc:sqlite:sqlite/GROUP.db
        driverClassName: org.sqlite.JDBC
    jpa:
        database-platform: cn.fintechstar.traddc.constant.SQLiteDialect
        show-sql: true
    redis:
        database: 0
#        host: 10.10.10.20
#        port: 5005
        host: 52.66.45.64
        port: 5006
        password: hugo123456
        timeout: 2000
        pool:
            max-active: 10
            max-idle: 8
            min-idle: 0
    rabbitmq:
        listener:
            simple:
                acknowledge-mode: none   

candle: 
    sameCandleTime: 50
    maxSize: 10000       
    
sqlite:
    names: AUD_CAD,AUD_CHF,AUD_HKD,AUD_JPY,AUD_NZD,AUD_SGD,AUD_USD,CAD_CHF,CAD_HKD,CAD_JPY,CAD_SGD,CHF_HKD,CHF_JPY,CHF_ZAR,EUR_AUD,EUR_CAD,EUR_CHF,EUR_CZK,EUR_DKK,EUR_GBP,EUR_HKD,EUR_HUF,EUR_JPY,EUR_NOK,EUR_NZD,EUR_PLN,EUR_SEK,EUR_SGD,EUR_TRY,EUR_USD,EUR_ZAR,GBP_AUD,GBP_CAD,GBP_CHF,GBP_HKD,GBP_JPY,GBP_NZD,GBP_PLN,GBP_SGD,GBP_USD,GBP_ZAR,HKD_JPY,NZD_CAD,NZD_CHF,NZD_HKD,NZD_JPY,NZD_SGD,NZD_USD,SGD_CHF,SGD_HKD,SGD_JPY,TRY_JPY,USD_CAD,USD_CHF,USD_CNH,USD_CZK,USD_DKK,USD_HKD,USD_HUF,USD_INR,USD_JPY,USD_MXN,USD_NOK,USD_PLN,USD_SAR,USD_SEK,USD_SGD,USD_THB,USD_TRY,USD_ZAR,ZAR_JPY,FINCOIN_USD,SymbolBUTT
    AUD_CAD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/AUD_CAD.db
    AUD_CHF: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/AUD_CHF.db
    AUD_HKD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/AUD_HKD.db
    AUD_JPY:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/AUD_JPY.db
    AUD_NZD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/AUD_NZD.db
    AUD_SGD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/AUD_SGD.db
    AUD_USD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/AUD_USD.db
    CAD_CHF: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/CAD_CHF.db
    CAD_HKD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/CAD_HKD.db
    CAD_JPY:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/CAD_JPY.db
    CAD_SGD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/CAD_SGD.db
    CHF_HKD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/CHF_HKD.db
    CHF_JPY:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/CHF_JPY.db
    CHF_ZAR: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/CHF_ZAR.db
    EUR_AUD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_AUD.db
    EUR_CAD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_CAD.db
    EUR_CHF: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_CHF.db
    EUR_CZK: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_CZK.db
    EUR_DKK: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_DKK.db
    EUR_GBP:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_GBP.db
    EUR_HKD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_HKD.db
    EUR_HUF: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_HUF.db
    EUR_JPY: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_JPY.db
    EUR_NOK: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_NOK.db
    EUR_NZD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_NZD.db
    EUR_PLN: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_PLN.db
    EUR_SEK: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_SEK.db
    EUR_SGD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_SGD.db
    EUR_TRY: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_TRY.db
    EUR_USD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_USD.db
    EUR_ZAR:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/EUR_ZAR.db
    GBP_AUD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_AUD.db
    GBP_CAD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_CAD.db
    GBP_CHF: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_CHF.db
    GBP_HKD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_HKD.db
    GBP_JPY: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_JPY.db
    GBP_NZD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_NZD.db
    GBP_PLN: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_PLN.db
    GBP_SGD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_SGD.db
    GBP_USD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_USD.db
    GBP_ZAR:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/GBP_ZAR.db
    HKD_JPY:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/HKD_JPY.db
    NZD_CAD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/NZD_CAD.db
    NZD_CHF: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/NZD_CHF.db
    NZD_HKD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/NZD_HKD.db
    NZD_JPY: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/NZD_JPY.db
    NZD_SGD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/NZD_SGD.db
    NZD_USD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/NZD_USD.db
    SGD_CHF: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/SGD_CHF.db
    SGD_HKD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/SGD_HKD.db
    SGD_JPY:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/SGD_JPY.db
    TRY_JPY: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/TRY_JPY.db
    USD_CAD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_CAD.db
    USD_CHF: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_CHF.db
    USD_CNH: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_CNH.db
    USD_CZK:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_CZK.db
    USD_DKK: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_DKK.db
    USD_HKD: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_HKD.db
    USD_HUF:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_HUF.db
    USD_INR:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_INR.db
    USD_JPY:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_JPY.db
    USD_MXN: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_MXN.db
    USD_NOK:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_NOK.db
    USD_PLN:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_PLN.db
    USD_SAR: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_SAR.db
    USD_SEK: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_SEK.db
    USD_SGD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_SGD.db
    USD_THB: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_THB.db
    USD_TRY: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_TRY.db
    USD_ZAR: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/USD_ZAR.db
    ZAR_JPY: 
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/ZAR_JPY.db
    FINCOIN_USD:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/FINCOIN_USD.db
    SymbolBUTT:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:sqlite/SymbolBUTT.db

mq:
    host: 52.66.45.64
    port: 5672
    username: demo
    password: demo
    vhost: /demo
    signalExchange: signal_grp
    instantExchange: t_node_grp
    queue:
        historySignalReq: HISTDATA_REQ
        historySignalAns: DATACENTRE_ANS.msg.
    instantSignalQueue: 
            AUD_CAD: AUD_CAD.DC
            AUD_CHF: AUD_CHF.DC
            AUD_HKD: AUD_HKD.DC
            AUD_JPY: AUD_JPY.DC
            AUD_NZD: AUD_NZD.DC
            AUD_SGD: AUD_SGD.DC
            AUD_USD: AUD_USD.DC
            CAD_CHF: CAD_CHF.DC
            CAD_HKD: CAD_HKD.DC
            CAD_JPY: CAD_JPY.DC
            CAD_SGD: CAD_SGD.DC
            CHF_HKD: CHF_HKD.DC
            CHF_JPY: CHF_JPY.DC
            CHF_ZAR: CHF_ZAR.DC
            EUR_AUD: EUR_AUD.DC
            EUR_CAD: EUR_CAD.DC
            EUR_CHF: EUR_CHF.DC
            EUR_CZK: EUR_CZK.DC
            EUR_DKK: EUR_DKK.DC
            EUR_GBP: EUR_GBP.DC
            EUR_HKD: EUR_HKD.DC
            EUR_HUF: EUR_HUF.DC
            EUR_JPY: EUR_JPY.DC
            EUR_NOK: EUR_NOK.DC
            EUR_NZD: EUR_NZD.DC
            EUR_PLN: EUR_PLN.DC
            EUR_SEK: EUR_SEK.DC
            EUR_SGD: EUR_SGD.DC
            EUR_TRY: EUR_TRY.DC
            EUR_USD: EUR_USD.DC
            EUR_ZAR: EUR_ZAR.DC
            GBP_AUD: GBP_AUD.DC
            GBP_CAD: GBP_CAD.DC
            GBP_CHF: GBP_CHF.DC
            GBP_HKD: GBP_HKD.DC
            GBP_JPY: GBP_JPY.DC
            GBP_NZD: GBP_NZD.DC
            GBP_PLN: GBP_PLN.DC
            GBP_SGD: GBP_SGD.DC
            GBP_USD: GBP_USD.DC
            GBP_ZAR: GBP_ZAR.DC
            HKD_JPY: HKD_JPY.DC
            NZD_CAD: NZD_CAD.DC
            NZD_CHF: NZD_CHF.DC
            NZD_HKD: NZD_HKD.DC
            NZD_JPY: NZD_JPY.DC
            NZD_SGD: NZD_SGD.DC
            NZD_USD: NZD_USD.DC
            SGD_CHF: SGD_CHF.DC
            SGD_HKD: SGD_HKD.DC
            SGD_JPY: SGD_JPY.DC
            TRY_JPY: TRY_JPY.DC
            USD_CAD: USD_CAD.DC
            USD_CHF: USD_CHF.DC
            USD_CNH: USD_CNH.DC
            USD_CZK: USD_CZK.DC
            USD_DKK: USD_DKK.DC
            USD_HKD: USD_HKD.DC
            USD_HUF: USD_HUF.DC
            USD_INR: USD_INR.DC
            USD_JPY: USD_JPY.DC
            USD_MXN: USD_MXN.DC
            USD_NOK: USD_NOK.DC
            USD_PLN: USD_PLN.DC
            USD_SAR: USD_SAR.DC
            USD_SEK: USD_SEK.DC
            USD_SGD: USD_SGD.DC
            USD_THB: USD_THB.DC
            USD_TRY: USD_TRY.DC
            USD_ZAR: USD_ZAR.DC
            ZAR_JPY: ZAR_JPY.DC
            FINCOIN_USD: FINCOIN_USD.DC
            SymbolBUTT: SymbolBUTT.DC